export { default as HomePage } from './Home';
export { default as NotFoundPage } from './NotFoundPage';
export { default as AboutPage } from './AboutPage';
export { default as LoginPage } from './LoginPage';
export { default as RegisterPage } from './RegisterPage';
export { default as GamePage } from './GamePage';
export { default as DashboardPage } from './DashboardPage';
export { default as GameLibraryPage } from './GameLibraryPage';
export { default as AchievementPage } from './AchievementPage';
